# Setup
title:        纪念与祭奠 | 冬雪篇 
tagline:      "他们说：不如意事常八九" 
tagline:      "谨以此篇致小曾，致自己" 
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       wfnian
  url:        wfnian.top 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown